-- Wake's data model, version 1: the SwiftData models of the macOS app as SQLite.
-- Table and column names are the Mac field names, so data can move between the
-- apps (and sync later) without a mapping layer.
--
-- Conventions:
--   ids      UUID text, lowercase ("3f2b…"), generated by the app
--   dates    REAL, seconds since 1970-01-01 UTC (Swift's Date.timeIntervalSince1970)
--   urls     TEXT, absolute
--   bools    INTEGER 0/1
-- The macOS store is SwiftData's own (Core Data tables named Z…); these are the
-- same fields, not the same file.

PRAGMA foreign_keys = ON;

-- A thread: an ordered list of columns plus a title. Resolved threads keep their
-- columns so Moments can show what was found.
CREATE TABLE ThreadRecord (
    id              TEXT PRIMARY KEY,
    customTitle     TEXT,
    -- Last computed title, so lists don't need live pages.
    title           TEXT NOT NULL,
    createdAt       REAL NOT NULL,
    -- Moves only while it's the thread you're in.
    lastActiveAt    REAL NOT NULL,
    focusedIndex    INTEGER NOT NULL DEFAULT 0,
    isResolved      INTEGER NOT NULL DEFAULT 0,
    outcome         TEXT,
    resolvedAt      REAL,
    -- Developer mode chosen for this thread; NULL is automatic.
    developerMode   INTEGER
);

CREATE TABLE ColumnRecord (
    threadID        TEXT NOT NULL REFERENCES ThreadRecord(id) ON DELETE CASCADE,
    -- Position in the trail, from 0.
    "order"         INTEGER NOT NULL,
    url             TEXT NOT NULL,
    title           TEXT NOT NULL,
    -- Share of the stage width, when the user resized the column.
    widthFraction   REAL,
    PRIMARY KEY (threadID, "order")
);

-- One entry per URL, bumped on each visit.
CREATE TABLE VisitRecord (
    url             TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    visitedAt       REAL NOT NULL,
    visitCount      INTEGER NOT NULL DEFAULT 1,
    -- The browser this was imported from ("Chrome", "Firefox"…); NULL for Wake's own.
    source          TEXT,
    -- The address lowercased, without its scheme: what History's search matches.
    address         TEXT NOT NULL DEFAULT ''
);
CREATE INDEX VisitRecord_visitedAt ON VisitRecord (visitedAt DESC);
CREATE INDEX VisitRecord_address ON VisitRecord (address);

-- Something searched for, with the engine's results page to go back to.
CREATE TABLE SearchRecord (
    id              INTEGER PRIMARY KEY,
    query           TEXT NOT NULL,
    -- The engine's name ("Google", "DuckDuckGo"…).
    engine          TEXT NOT NULL,
    url             TEXT NOT NULL,
    searchedAt      REAL NOT NULL,
    source          TEXT
);
CREATE INDEX SearchRecord_searchedAt ON SearchRecord (searchedAt DESC);

-- A pinned web app in the capsule.
CREATE TABLE PinnedAppRecord (
    id              TEXT PRIMARY KEY,
    url             TEXT NOT NULL,
    title           TEXT NOT NULL,
    "order"         INTEGER NOT NULL
);

-- A saved moment: a page as it was when saved, where you were in it, what you'd
-- selected, and why.
CREATE TABLE MomentRecord (
    id              TEXT PRIMARY KEY,
    url             TEXT NOT NULL,
    title           TEXT NOT NULL DEFAULT '',
    createdAt       REAL NOT NULL,
    -- "Why": the user's own reason.
    note            TEXT,
    -- The selection when saved, re-highlighted on restore.
    selectedText    TEXT,
    -- A little of the text just before the selection, to find the right occurrence.
    selectionPrefix TEXT,
    scrollY         REAL NOT NULL DEFAULT 0,
    -- How far down the page (0…1), used when the page's height has changed.
    scrollFraction  REAL NOT NULL DEFAULT 0,
    -- SHA-256 (hex) of the page's visible text when saved, whitespace collapsed.
    contentHash     TEXT NOT NULL DEFAULT '',
    -- The page's visible text when saved (at most 40 000 characters).
    contentText     TEXT NOT NULL DEFAULT '',
    -- When to bring it back up; NULL = only when you're on its site.
    resurfaceAt     REAL,
    lastOpenedAt    REAL,
    openCount       INTEGER NOT NULL DEFAULT 0,
    lastCheckedAt   REAL,
    -- Set by the background check when the page no longer matches what was saved.
    changedAt       REAL,
    changeSummary   TEXT,
    isArchived      INTEGER NOT NULL DEFAULT 0,
    -- The thread it was saved from.
    threadID        TEXT
);
CREATE INDEX MomentRecord_createdAt ON MomentRecord (createdAt DESC);

PRAGMA user_version = 1;
